server:
  port: 8085
  servlet:
    context-path: /learnlo
spring:
  application:
    name: learnlo-backend
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://learnlo-lms-db.c3mm0kmcmilo.us-east-2.rds.amazonaws.com:5432/learnlo_lms_db
    username: postgres
    password: Password12